### ISSUE TITLE
Feature Proposal: Introduce HtmxSwapService for Out-of-Band Swapping

### ISSUE THREAD

**Issue by tanczosm** [egil/Htmxor#13]
**Description:**

Service Name: HtmxSwapService (Alternative names: OOBSwapService, ComponentSwapService)

Currently, there's a need for a mechanism to perform Out-of-Band (OOB) swaps in response to htmx requests. This feature request proposes the addition of a scoped service named HtmxSwapService to fulfill this requirement.  While it is possible to add OOB swaps anywhere you want, they still need to be largely done on HTMX requests rather than full page renders.  

A service would then allow you to easily inject the components / html you want to render on an out-of-band basis.  It could also be utilized by third-party components as well to add interactivity to the page.  

Htmx supports the following swaps:

- [Out-of-band swaps](https://htmx.org/docs/#oob_swaps)
- [Head configuration swaps (2.0)](https://v2-0v2-0.htmx.org/docs/#head)

**Functionality:**

- Provides a method to add razor components with a parameter dictionary/object or accepts RenderFragment as a parameter.
- Components to render/renderfragments are stored to a list
- Renders the fragments at the end of the HTTP response specifically in response to htmx requests.  Can be done at the very end of the request, after the closing body tag.

**Example Usage:**

- Inject an updated navbar that gets rendered with the response on an HTMX request
- Inject flash/toast/notification messages that appear on screen in response to an error, warning, or other message
- Update header tags to reflect the current page state
- Inject any new content that can piggyback on top of any other htmx request (for example update a notifications counter for the user)

**Comment by egil** [comment]
To understand your proposed solution, can you create some example code that shows a few of the different scenarios (don't implement it, just show how the API would work)?

**Comment by tanczosm** [comment]
I think this would probably require some discussion but on a base level users would need to be able to add components/content for publishing as OOB swaps.  

If it's kept generic where all this content ultimately gets injected into a section outlet then there is no need to get complicated by specifically handling OOB swaps.  Instead create a base set of razor components that mirror htmx principles.  The name HtmxSwapService may not be appropriate then but I'm not sure what else I'd go with.

```csharp

public interface IHtmxSwapService
{
    // Method to add a Razor component with a parameter dictionary/object
    void AddComponent<TComponent>(Dictionary<string, object> parameters = null ) where TComponent : IComponent;

    // Method to add a Razor component with RenderFragment as a parameter
    void AddComponent<TComponent>(RenderFragment renderFragment) where TComponent : IComponent;

   // Add Raw html content
   void AddContent (string content)

   // Render the list of components to a ??? type so that it is included in the output of the page
   ??? Render ();
}

```

Then maybe we create a Razor Component for swaps.  Something like:

```Razor
<HxSwappable Id="alerts" SwapStyle="SwapStyle.OuterHTML" CssSelector="whatever">
    ... Content here
</HxSwappable>
```

**Comment by tanczosm** [comment]
A few thoughts on  HxSwappable after putting it into Rizzy.  It does work well as a defined OOB swap component but the swap service only works adding content outside of blazor page lifecycle methods.  My hope was to be able to render swaps at the end of the response after the initial page render on htmx requests.  Unfortunately blazor response rendering was completing before the SwapService contains any content if any of the add methods are called inside of a page.

Section outlets aren't really a solution because ideally you could piggyback and render swaps on *any* htmx request to get page content updates rather than what might be in a full page request.

Htmxor might work as you have better control over the renderer.

**Comment by egil** [comment]
Interesting. Can you share an example that I can test against and perhaps your ideal solution?

**Comment by egil** [comment]
Is this still relevant @tanczosm?

**Comment by tanczosm** [comment]
Let's close it for now.
