### ISSUE TITLE
UseEmbeddedHtmx?

### ISSUE THREAD

**Issue by StefH** [egil/Htmxor#60]
The comment in HtmxHeadOutlet is as follows:
``` c#
/// <summary>
/// Gets or sets whether or not to add the scripts thats that reference the embedded version of Htmx. Default is <see langword="true"/>.
/// </summary>
/// <remarks>
/// If this set to <see langword="false"/>, include the <c>_content/Htmxor/htmxor.js</c> your application manually.
/// </remarks>
[Parameter] public bool UseEmbeddedHtmx { get; set; } = true;
```

But when setting this to **false**, in addition to "include the <c>_content/Htmxor/htmxor.js</c> your application manually", I also need to reference the javascript file for htmx myself, correct?

(BTW I don't understand why I would need to include the <c>_content/Htmxor/htmxor.js</c> your application manually) ?

**Comment by egil** [comment]
The remarks were wrong. If you look at the rest of the code, you see it only excludes the embedded htmx.js file. So, now the docs are right, and as the docs say, you do need to reference your own version of htmx.
