### ISSUE TITLE
Split package: Htmxor.Declarations (or Htmxor.Abstractions) and Htmxor

### ISSUE THREAD

**Issue by megafetis** [egil/Htmxor#61]
Is it possible to split package to two: Htmxor.Declarations (or Htmxor.Abstractions) and Htmxor ?
To use some attributes, interfaces in webassembly side without including serverside features

**Comment by egil** [comment]
I'm not opposed to it, but can you share more details about the use case?

**Comment by megafetis** [comment]
Thank @egil !
Example:
Solution, where:
- aspnet core project as render server
- wasm host project
- blazor projects as parts of web app where may be ht-* markup and direct routing pages.
- some scenarios involve only rendering and further use of htmx (not wasm)
- some scenarios involve rendering and further launch wasm host.
When runs aspnet core host, it registers routing for htmx. 
But when the wasm host is launched, most of the code intended for the server gets into the client part.

**Comment by egil** [comment]
Sorry, I still not follow exactly what you are trying to do. Can you elaborate?

**Comment by megafetis** [comment]
I just trying to reduce size of wasm payload. Now problem is solving by IL trimming. So problem is not critical. In future splitting packages would be an elegant solution.

**Comment by egil** [comment]
> I just trying to reduce size of wasm payload. Now problem is solving by IL trimming. So problem is not critical. In future splitting packages would be an elegant solution.

Thanks for the update. I will want to avoid unnecessary complexity so will probably not split up into two packages before I needed to.

**Comment by megafetis** [comment]
Ok! Thanks for feedback
